### PR TITLE
Update to accommodate bma method for trend_assessment

### PR DESCRIPTION
**Pull request by 03rcooke**
I've updated `species_assessment` and `trend_assessment` so they can be applied to either the lambda method or bma method (via the `method` argument).

I had to add `--no-manual` to the Check Package options, else it produces a build error that is unfixable on my OS as far as I can tell: "Error in texi2dvi(file = file, pdf = TRUE, clean = clean, quiet = quiet, : pdflatex is not available"

### CODE REVIEW

**Comment by AugustT** [comment]
Was the no manual thing a change you made only on your pc? Or did you change the way Travis runs?

**Comment by AugustT** [comment]
@03rcooke can you bump version number?

**Comment by AugustT** [comment]
happy for you to merge once checks pass

**Comment by 03rcooke** [comment]
@AugustT I'm not sure I have the right to merge the changes, I just don't see a Merge pull request box.

**Pull request merged**
